# Generated by Django 4.1.2 on 2022-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_ad_author_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Tanks', 'Танки'), ('Hils', 'Хилы'), ('DD', 'ДД'), ('Traders', 'Торговцы'), ('Guildmaster', 'Гилдмастеры'), ('Questgivers', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Leatherworkers', 'Кожевники'), ('Potions', 'Зельевары'), ('Spell masters', 'Мастера заклинаний')], default='Tanks', max_length=16),
        ),
    ]
