# Generated by Django 4.1.2 on 2022-10-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_ad_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='uploads',
        ),
    ]
