# Generated by Django 4.1.2 on 2022-10-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_ad_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='uploads',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
