# Generated by Django 4.1.2 on 2022-10-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_ad_uploads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='to_ad',
            new_name='ad',
        ),
    ]
