# Generated by Django 4.1.2 on 2022-10-22 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0007_alter_ad_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Tanks', 'Танки'), ('Hils', 'Хилы'), ('DD', 'ДД'), ('Traders', 'Торговцы'), ('Guildmaster', 'Гилдмастеры'), ('Questgivers', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Leatherworkers', 'Кожевники'), ('Potions', 'Зельевары'), ('Spell masters', 'Мастера заклинаний')], default='Tanks', max_length=16, verbose_name='Категория объявления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.TextField(verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='uploads',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загрузить файл'),
        ),
        migrations.AlterField(
            model_name='response',
            name='accept',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='response',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.ad', verbose_name='Отклик на объявление'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(verbose_name='Содержание отклика'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика'),
        ),
    ]
