# Generated by Django 4.1.2 on 2022-10-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_ad_author_alter_ad_category_alter_ad_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='notaccept',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='accept',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
